version: "3.2"
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
  db:
    image: 'mongo'
    container_name: MONGODB  
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  
      
  